import Container from '@/components/Container/Container';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Vote from '@/components/Vote/Vote';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Container>
        <h1>Hello world</h1>
        <Vote totalGlobalLikes={10} />
      </Container>
    </div>
  );
}
