import Profile from '@/components/Profile/Profile';
import Container from '@/components/Container/Container';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const user = {
  name: 'Abul Hossain',
  title: 'Developer at dorik',
  details: 'I Love React',
};

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Container>
        <h1>Hello world</h1>

        <Profile name={user.name} title={user.title} details={user.details} />
      </Container>
    </div>
  );
}
